export type Article = { slug: string; category: string; minutes: string; title: string; deck: string; sections: { heading?: string; body: string[]; code?: string; aside?: string }[]; next: { label: string; href: string } };

export const articles: Article[] = [
  { slug: "disposable-worktrees", category: "Isolation", minutes: "7 min", title: "Why every coding-agent job gets a disposable worktree", deck: "A Git repository is valuable state, not an execution sandbox. DeadDrop protects the former without pretending it protects the whole machine.", sections: [
    { body: ["Most coding-agent demos begin with the same innocent instruction: change into a project directory and let the model work. That is also where the developer may have half-finished edits, untracked notes, generated files, ignored credentials, and a branch whose exact state matters.", "The problem is not that agents always destroy work. The problem is that the failure boundary is vague. A failed run can leave useful changes mixed with partial experiments, while a diff can confuse pre-existing work with agent output."] },
    { heading: "Choose a baseline before execution", body: ["DeadDrop resolves the repository root and current HEAD before the agent starts. That commit is the job baseline. It creates a detached Git worktree in a temporary directory and runs the agent there."], code: "git rev-parse --show-toplevel\ngit rev-parse HEAD\ngit worktree add --detach /tmp/deaddrop-job/workspace <baseline>", aside: "The source workspace is not a rollback target. DeadDrop does not edit it, so it does not need to guess how to restore it." },
    { heading: "Capture a complete, scoped patch", body: ["After the agent and verification commands finish, the worker stages changes only inside the temporary worktree. Staging is an observation technique here, not a step toward committing."], code: "git add -A -- .\ngit diff --binary --relative <baseline> -- .\ngit diff --name-only --relative -z <baseline> -- ." },
    { heading: "Cleanup is part of correctness", body: ["The temporary worktree is removed after patch capture, whether the job completes, fails, times out, or is cancelled. This prevents abandoned worktrees from accumulating administrative records and disk usage."] },
    { heading: "What this does not isolate", body: ["A worktree is a repository-state boundary. It is not a container, virtual machine, permission boundary, or network sandbox. The agent still inherits the worker user's filesystem, tools, environment, credentials, and network access.", "DeadDrop isolates source Git state. Operators still need a dedicated non-root user, intentionally limited credentials, and a manifest containing only repositories the agent may access."] },
  ], next: { label: "Next: A receipt should be evidence, not agent prose", href: "/blog/evidence-based-receipts" } },
  { slug: "evidence-based-receipts", category: "Receipts", minutes: "6 min", title: "A receipt should be evidence, not agent prose", deck: "Agent summaries are useful. Agent claims about files, tests, and success are not enough to operate a reliable queue.", sections: [
    { body: ["When a coding agent finishes, it explains what it believes it did. That explanation can describe intent, tradeoffs, blockers, and decisions. It is also produced by the same fallible process that made the change.", "If a job system copies that explanation directly into changed files and tests passed, it turns a narrative into an audit record. The interface looks structured, but the trust model has not improved."] },
    { heading: "Split subjective and observable fields", body: ["DeadDrop asks for a structured receipt, then deliberately replaces the fields the worker can observe. Summaries, notes, and blockers come from the agent. Changed files come from Git. Verification comes from worker commands. Status comes from observed exit state."] },
    { heading: "Git is the changed-file authority", body: ["The worker asks Git which paths differ from the known baseline. That includes files the agent forgot to mention and excludes files it claimed to change but did not. The dashboard stores the binary Git diff rather than reconstructing edits from a model response."] },
    { heading: "Verification belongs outside the prompt", body: ["The manifest accepts trusted verification commands. The worker runs them after the agent in the isolated workspace and records each exact command, status, and exit code."], code: "{\n  \"alias\": \"default\",\n  \"path\": \"/projects/api\",\n  \"verify\": [\"pytest -q\", \"ruff check .\"]\n}", aside: "Configuration is a trust boundary. Verification commands are local operator input and can execute arbitrary code." },
    { heading: "Fields need provenance", body: ["The goal is not to distrust every sentence an agent writes. It is to avoid asking one source to be both actor and auditor. Summaries explain. Git enumerates. Commands verify. Process state decides."] },
  ], next: { label: "Next: Leases make local agents recoverable", href: "/blog/leases-for-local-agents" } },
  { slug: "leases-for-local-agents", category: "Recovery", minutes: "8 min", title: "Leases make local agents recoverable", deck: "A local worker can sleep, lose Wi-Fi, crash, or return late. A durable queue needs ownership that expires safely.", sections: [
    { body: ["The simplest queue fetches the next row and marks it running. That works until the process disappears before completion. The database now contains a running job that no worker owns.", "Local coding workers make this common. Laptops suspend. Networks change. Agent CLIs hang. Users kill terminals. A reliable design treats worker disappearance as normal."] },
    { heading: "An attempt owns the job temporarily", body: ["When a worker claims a job, the server generates a unique attempt ID, increments the attempt number, and assigns a lease expiration. Every log, heartbeat, and result includes that ID."], code: "job 42\nstatus: running\nattempt_number: 3\nattempt_id: 7f9b…\nlease_expires_at: 12:01:00Z" },
    { heading: "Heartbeats renew, polls recover", body: ["The worker sends a heartbeat every five seconds. A successful heartbeat moves the sixty-second lease forward. Before another claim, the server scans for expired running jobs, marks each attempt lost, and returns its job to queued.", "The next claim gets a new attempt ID. If the old worker reconnects, the server rejects its late result. It cannot overwrite newer work."] },
    { heading: "Cancellation belongs in ownership", body: ["Cancelling a running job requires the current attempt to cooperate. The next heartbeat returns the cancellation signal, the worker kills the command process group, captures any partial patch, and acknowledges a cancelled result."], aside: "Cancellation rides the existing outbound heartbeat path. No second control channel or inbound connection is required." },
    { heading: "Terminal delivery needs durability", body: ["If a job finishes while the server is unreachable, the worker atomically stores the terminal payload in a user-only pending-results directory and replays it before claiming more work.", "Leases turn failure into explicit state: running attempt, renewed lease, lost attempt, new attempt, rejected stale write. That vocabulary makes operator behavior predictable."] },
  ], next: { label: "Explore the full architecture", href: "/docs/architecture" } },
];
