import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Documentation" };
const sections = [
  ["requirements", "01", "Requirements", <p key="r">You need Docker with Compose, Git, and either a released worker binary or Go 1.22+. Gemini CLI is only required for Gemini mode.</p>],
  ["server", "02", "Start a durable server", <div key="server"><p>The Compose stack runs FastAPI and PostgreSQL. Secrets stay in your shell environment; database state stays in a named volume.</p><pre><code>{`export OWNER_TOKEN="$(openssl rand -hex 32)"\nexport WORKER_TOKEN="$(openssl rand -hex 32)"\nexport POSTGRES_PASSWORD="$(openssl rand -hex 32)"\ndocker compose up -d --build`}</code></pre><p>Open <code>http://localhost:8000/login</code> and enter <code>OWNER_TOKEN</code>.</p></div>],
  ["worker", "03", "Build or download the worker", <div key="worker"><pre><code>{`cd worker\ngo build -o deaddrop-worker .\n./deaddrop-worker version`}</code></pre><p>Tagged releases provide Linux, macOS, and Windows binaries with SHA-256 checksums.</p></div>],
  ["manifest", "04", "Create the trust boundary", <div key="manifest"><p>The manifest is local. The server receives the alias <code>default</code>, not the absolute path.</p><pre><code>{`./deaddrop-worker init \\\n  --repo /absolute/path/to/project \\\n  --verify "go test ./..."`}</code></pre></div>],
  ["run", "05", "Run the worker", <div key="run"><pre><code>{`./deaddrop-worker run \\\n  --server http://localhost:8000 \\\n  --token "$WORKER_TOKEN" \\\n  --manifest deaddrop.manifest.json \\\n  --agent gemini`}</code></pre><p>Use <code>--agent mock</code> for the bundled deterministic demo, or custom mode for another CLI.</p></div>],
  ["receipts", "06", "Read the receipt", <div className="definitions" key="receipts"><div><strong>Summary</strong><p>The agent&apos;s human-readable account.</p></div><div><strong>Changed files</strong><p>Derived from the baseline-relative Git diff.</p></div><div><strong>Verification</strong><p>Commands and exit states observed by the worker.</p></div><div><strong>Patch</strong><p>A scoped binary diff; never auto-applied.</p></div></div>],
  ["apply", "07", "Apply a result deliberately", <div key="apply"><p>Download the patch, commit or stash unrelated work, then inspect it from the configured workspace.</p><pre><code>{`git apply --stat /path/to/job.patch\ngit apply --check /path/to/job.patch\ngit apply /path/to/job.patch`}</code></pre></div>],
];

export default function Docs() { return <><section className="page-hero"><p className="eyebrow">Documentation</p><h1>From zero to a verified local-agent queue.</h1><p>Run the server, configure one trusted Git workspace, and make the worker prove what changed.</p></section><div className="docs-layout"><aside>{sections.map(([id,,title]) => <a key={String(id)} href={`#${id}`}>{String(title)}</a>)}</aside><article className="docs-content">{sections.map(([id,n,title,content]) => <section id={String(id)} key={String(id)}><span>{String(n)}</span><h2>{String(title)}</h2>{content}</section>)}<section><span>08</span><h2>Go deeper</h2><div className="link-stack"><Link href="/docs/architecture"><strong>Architecture</strong><small>Attempts, worktrees, receipts, and trust boundaries</small></Link><Link href="https://github.com/haroon0x/DeadDrop/blob/main/docs/deployment.md"><strong>Deployment guide</strong><small>Compose, Render, upgrades, secrets, and backups</small></Link></div></section></article></div></> }
